name: .NET Build & Publish NuGet V2
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore /property:Configuration=Release
    - name: Build
      run: dotnet build  --configuration Release --no-restore -o out
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal -o out

    - name: Push generated package 
      run: dotnet nuget push ./**/out/*.nupkg -k ${{ secrets.NUGET_PUBLISH }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
    
 #   - uses: actions/checkout@master
 #   - uses: codecov/codecov-action@v2
 #     with:
 #       fail_ci_if_error: true # optional (default = false)
